name: user_repository
description: a repository for managing user data.
version: 0.0.1
publish_to: 'none' # this package is not meant to be published

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  stock_repository:
    path: ../stock_repository/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

