
import '../models/models.dart';
import 'costants.dart';

Iterable<Item> items = [
  Item(
    image: 'assets/images/item1.jpg',
    id: '1',
    name: 'Nice necklace',
    description: 'This is a beautiful and elegant necklace crafted with the finest materials. It features intricate detailing and a sophisticated design that makes it perfect for both casual and formal occasions. The craftsmanship reflects the highest standards of jewelry making.',
    grossWeight: 10.0,
    netWeight: 8.0,
    purity: 22,
    type: DataFields.necklace,
    size: '18 inches',
    material: DataFields.gold, 
  ),
  Item(
    image: 'assets/images/item2.jpg',
    id: '2',
    name: 'Awesome ring',
    description: 'A stunning ring that showcases exceptional artistry and premium quality. This piece combines traditional design elements with modern aesthetics, creating a timeless accessory that will be cherished for generations. Perfect for special moments and celebrations.',
    grossWeight: 15.0,
    netWeight: 12.0,
    purity: 18,
    type: DataFields.ring,
    size: 'Size 8',
    material: DataFields.silver, 
  ),
  Item(
    image: 'assets/images/item3.jpg',
    id: '3',
    name: 'Legendary bracelet',
    description: 'This legendary bracelet represents the pinnacle of jewelry craftsmanship. Every detail has been carefully considered, from the selection of materials to the final finishing touches. It embodies luxury and sophistication in every aspect of its design.',
    grossWeight: 20.0,
    netWeight: 18.0,
    purity: 22,
    type: DataFields.bracelet,
    size: '7.5 inches',
    material: DataFields.gold, 
  ),
  Item(
    image: 'assets/images/item4.jpg',
    id: '4',
    description: 'A masterpiece of jewelry design that combines elegance with contemporary style. This bracelet features innovative techniques and premium materials, creating a piece that stands out in any collection. Perfect for those who appreciate fine craftsmanship.',
    name: 'Chronical bracelet',
    netWeight: 15.0,
    grossWeight: 20.0,
    purity: 18,
    type: DataFields.bracelet,
    size: '8 inches',
    material: DataFields.silver,
  ),
  Item(
    image: 'assets/images/item5.jpg',
    id: '5',
    description: 'This anklet represents the perfect blend of tradition and modernity. Crafted with attention to detail, it features delicate patterns and superior quality materials. The design ensures comfort while maintaining an elegant appearance that complements any outfit.',
    name: 'Chronical anklet',
    netWeight: 11.0,
    grossWeight: 21.0,
    purity: 18,
    type: DataFields.anklet,
    size: '10 inches',
    material: DataFields.silver,
  ),
  Item(
    image: 'assets/images/item6.jpg',
    id: '6',
    description: 'A spectacular necklace that captures attention with its breathtaking beauty and exceptional quality. Every element has been carefully crafted to create a piece that is both visually stunning and comfortable to wear. This necklace is a true testament to fine jewelry making.',
    name: 'Spectacular necklace',
    netWeight: 15.0,
    grossWeight: 20.0,
    purity: 22,
    type: DataFields.necklace,
    size: '20 inches',
    material: DataFields.gold,
  ),
  Item(
    image: 'assets/images/item7.jpg',
    id: '7',
    description: 'An amazing necklace that showcases the perfect harmony between classic elegance and contemporary design. The attention to detail is evident in every aspect, from the material selection to the intricate patterns. This piece is designed to be both beautiful and durable.',
    name: 'Amazing necklace',
    netWeight: 15.0,
    grossWeight: 210,
    purity: 18,
    type: DataFields.necklace,
    size: '16 inches',
    material: DataFields.silver,
  ),
  Item(
    image: 'assets/images/item8.jpg',
    id: '8',
    description: 'A muscular bracelet that combines strength and beauty in perfect harmony. The robust design ensures durability while maintaining an elegant appearance. Crafted with premium materials and exceptional attention to detail, this bracelet is built to last.',
    name: 'Muscular bracelet',
    netWeight: 15.0,
    grossWeight: 20.0,
    purity: 18,
    type: DataFields.bracelet,
    size: '8.5 inches',
    material: DataFields.silver,
  ),
];
