
import '../models/models.dart';
import 'costants.dart';

Iterable<Item> items = [
  Item(
    image: 'assets/images/item1.jpg',
    id: '1',
    name: 'Nice necklace',
    description: 'This is a description of this item from the shop, it is very nice and beautiful',
    grossWeight: 10.0,
    weight: 8.0,
    type: DataFields.necklace,
    material: DataFields.gold, 
  ),
  Item(
    image: 'assets/images/item2.jpg',
    id: '2',
    name: 'Awesome ring',
    description: 'This is a description of this item from the shop, ',
    grossWeight: 15.0,
    weight: 12.0,
    type: DataFields.ring,
    material: DataFields.silver, 
  ),
  Item(
    image: 'assets/images/item3.jpg',
    id: '3',
    name: 'Legendary bracelet',
    description: 'This is a description of this item from the shop, ',
    grossWeight: 20.0,
    weight: 18.0,
    type: DataFields.bracelet,
    material: DataFields.gold, 
  ),
  Item(
    image: 'assets/images/item4.jpg',
    id: '4',
    description: 'This is a description of this item from the shop, ',
    name: 'Chronical bracelet',
    weight: 15.0,
    grossWeight: 20.0,
    type: DataFields.bracelet,
    material: DataFields.silver,
  ),
  Item(
    image: 'assets/images/item5.jpg',
    id: '5',
    description: 'This is a description of this item from the shop, ',
    name: 'Chronical anklet',
    weight: 11.0,
    grossWeight: 21.0,
    type: DataFields.anklet,
    material: DataFields.silver,
  ),
  Item(
    image: 'assets/images/item6.jpg',
    id: '6',
    description: 'This is a description of this item from the shop, ',
    name: 'Spectacular necklace',
    weight: 15.0,
    grossWeight: 20.0,
    type: DataFields.necklace,
    material: DataFields.gold,
  ),
  Item(
    image: 'assets/images/item7.jpg',
    id: '7',
    description: 'This is a description of this item from the shop, ',
    name: 'Amazing necklace',
    weight: 15.0,
    grossWeight: 210,
    type: DataFields.necklace,
    material: DataFields.silver,
  ),
  Item(
    image: 'assets/images/item8.jpg',
    id: '8',
    description: 'This is a description of this item from the shop, ',
    name: 'Muscular bracelet',
    weight: 15.0,
    grossWeight: 20.0,
    type: DataFields.bracelet,
    material: DataFields.silver,
  ),
];
